name: Build with Maven

on:
  push:
    branches:
      -testbranch/*
    pull_requst:
      branches:
        -testbranch/*

      jobs:
        build:
          runs-on: ubuntu-latest
          timeout-minutes: 1

          steps:
            -uses: actions/checkout@v2
            -name: Setup Java
            uses: actions/setup-java@v2
            with:
              java-version: '11'
              distribution: 'adopt'
              cach: 'maven'
              -name: Build with Maven
              run: mvn -B package