name: Java Build with Maven

on:
  push:
    branches: [ testbranch,master ]
  pull_request:
    branches: [ testbranch,master ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes:2;

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml --fail-at-end
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1